### ISSUE TITLE
setting admin doesn't make the user admin

### ISSUE THREAD

**Issue by thecodeassassin** [juliendufresne/ansible-role-influxdb#1]
Hi,

I have the following users:

```
influxdb_users:
  - type: admin
    name: admin
    password: "secretpass"
  - type: user
    name: monitoring
    password: "somepass"
    rights:
      - "monitoring:WRITE"
```

setting the user type to admin doesn't make the user admin. When i use the shell script in the files folder it does seem to work. I think something went wrong when converting to the python script.
